name: Automated tests

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
          cache: "pip"

      - name: cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: cache venv
        uses: actions/cache@v3
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}

      - name: verify Chrome is installed
        run: |
          echo "Chrome version: $(google-chrome --version)"
          echo "Chrome path: $(which google-chrome)"      

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run tests
        run: |
          pytest -n 2 --tb=short -x tests/ # Уменьшаем параллелизм
          pkill -f chrome || true # Принудительно очищаем
          pkill -f chromedriver || true